### ISSUE TITLE
When No border the OSC not disappere

### ISSUE THREAD

**Issue by satpowers** [stax76/mpv.net#148] opened 2020-04-16 12:42 UTC
**Describe the bug**
When in no border window mode and OSC is auto, the OSC appers on mouse enter but it does not clear when leave window, it stay display

**To Reproduce**
1. Press b ( to be in no border mode)
2. move mouse to lower part of window
3. OSC appears, then move mouse out of window, the OSC sill ON

**Comment by stax76** [comment] 2020-04-17 11:19
It was working before but only with some workaround. It's probably a libmpv issue, I try to workaround and otherwise request support.

I notice there is a new top bar, I try to add full support for that too.

**Comment by stax76** [comment] 2020-04-18 15:07
Ok, the issue is that mpv does not auto hide the osc when the mouse left the window.

This could either be an issue in libmpv or the way how I use libmpv, the related code is to complex to understand easily and researching it might not be worth the effort. In the future I hope I will be able to debug and contribute to libmpv. It doesn't matter because such issues can usually be addressed with simple workarounds.

This issue actually was known to me and fixed with a workaround but this workaround stopped working when the new top bar feature was added to mpv.

The next build will have a better fix and I will post it in this thread when it's available, hopefully soon.

Now I have to investigate why the top bar window buttons don't work.

**Comment by stax76** [comment] 2020-04-19 19:08
New beta version is now available:

https://github.com/stax76/mpv.net#beta

**Closed by stax76** 2020-04-19 19:08 UTC
Labels: addressed in next release, bug
