### ISSUE TITLE
Dark mode looks weird on Windows 7

### ISSUE THREAD

**Issue by floppyD** [stax76/mpv.net#49] opened 2019-07-15 23:14 UTC
Letters are barely visible. Shouldn't they be white? And why does the font smoothing looks so "exaggerated"?
![mpv net 4 7 1 0](https://user-images.githubusercontent.com/29208110/61254901-b058d980-a73c-11e9-9569-a9f739e531d9.png)

**Comment by stax76** [comment] 2019-07-15 23:44
That colors that are too dark for you are OS theme colors which mpv.net follows.

Things you can do are:

change theme color in the OS or

disable dark mode in mpv.net

mpv.net might have room for improvement regarding this issue, I will have to think about it, one solution might be an option to let the user use a custom color instead of following the OS theme color.

**Comment by stax76** [comment] 2019-07-16 20:32
The next build will address the issue with:

- on Win 7 the theme color was hard coded to DarkSlateGrey because
  WPF was returning a bad color on Win 7, this was fixed by reading
  the theme color from the Registry on Win 7
- new option color-dark was added to overwrite the OS theme color used in dark mode
- new option color-light was added to overwrite the OS theme color used in non dark mode

Probably I will upload a new build tomorrow.

**Comment by stax76** [comment] 2019-07-17 17:04
Please try if the issue is solved.

- on Win 7 the theme color was hardcoded to DarkSlateGrey because
  WPF was returning a bad color on Win 7, this was fixed by reading
  the theme color from the Registry on Win 7
- new option color-dark was added to overwrite the OS theme color used in dark mode, find the option under 'General'
- new option color-light was added to overwrite the OS theme color used in non dark mode, find the option under 'General'

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by 44vince44** [comment] 2019-07-19 12:44
I'm testing all the  features i know, and everything seems ok. But I can't test anything on Win7. My setup is Win10. But I have an old laptop with a x86 Win7. and the beta is x64.

**Comment by floppyD** [comment] 2019-07-19 17:15
Well...
![mpv net 4 7 6 1](https://user-images.githubusercontent.com/29208110/61552967-9a466400-aa2f-11e9-9634-69f80c947b37.png)
![mpv net 4 7 6 1 1](https://user-images.githubusercontent.com/29208110/61552968-9a466400-aa2f-11e9-8ee5-a530ee810962.png)

**Comment by stax76** [comment] 2019-07-19 18:19
Maybe a Win 7 specific issue, debugging this will be much work as I have to use a Virtual Machine.

Does it look good if you override the theme color using the dark-color and light-color setting?

**Comment by floppyD** [comment] 2019-07-19 18:49
Yes, it does. Maybe you should make white the default color and make the OS theme color optional?
![mpv net 4 7 6 2](https://user-images.githubusercontent.com/29208110/61558148-9a009580-aa3c-11e9-8358-ace1360c97db.png)

**Comment by stax76** [comment] 2019-07-19 19:17
Yes, I might have to change the default.

I leave this ticket open until further investigation.

**Comment by stax76** [comment] 2019-07-21 00:54
What I did now is checking the theme/foreground color against the background color, in case both is black or both is white it is corrected to use orange.

**Comment by stax76** [comment] 2019-07-21 19:24
New release which addresses this issue is out, thanks for the feedback!

**Closed by stax76** 2019-07-21 19:24 UTC
