### ISSUE TITLE
Sometimes after going into full screen and out of it, OSC doesn't get shown

### ISSUE THREAD

**Issue by TETYYS** [stax76/mpv.net#26] opened 2019-06-16 10:27 UTC
You can interact with it, but you don't see what you're interacting with. Also things like status texts in upper left corner (for example, if you enable infinite file looping) don't appear.

**Comment by stax76** [comment] 2019-06-16 11:07
going in and out fullscreen isn't supposed to show the on screen controller, if you would like to behave it like this I can write you a small script.

Tools > Toggle infinite file looping

this should show a OSD message, it works for me, key is L which equals to shift+l.

**Comment by TETYYS** [comment] 2019-06-16 12:23
I mean, OSC doesn't show up after the bug even if i hover over the lower portion of the screen, or try to disable or enable it. It fixes it if you resize the window even a little bit

**Comment by stax76** [comment] 2019-06-16 12:45
Does it happen often? Things like this are very difficult to reproduce, debug and fix.

**Comment by stax76** [comment] 2019-06-16 13:11
Ah, you know C#. There is some ugly code in place because I could not figure out why the win32 mpv video window is not receiving window messages, I have to forward the messages.

If it happens to often I can try to find a better solution by asking the mpv developers and asking in a win32 forum.

<https://github.com/stax76/mpv.net/blob/master/mpv.net/WinForms/MainForm.cs#L330>

**Comment by TETYYS** [comment] 2019-06-16 14:07
It happens within less than 1 minute if I'm trying to trigger it by rapidly closing and reopening different files in a folder

**Comment by stax76** [comment] 2019-06-16 14:25
I'm trying to find out why the mpv window don't receive messages, spy++ shows it has the style WS_DISABLED, I think that's why it's not receiving messages.

**Comment by stax76** [comment] 2019-06-16 17:12
I created a ticket now on the mpv tracker.

https://github.com/mpv-player/mpv/issues/6762

**Comment by stax76** [comment] 2019-06-17 19:53
I've uploaded a new release due to a critical bug with the file association feature.

Regarding this issue I moved following:

https://github.com/stax76/mpv.net/blob/c93647841e3ae6025013a897c9cb0654597478cb/mpv.net/WinForms/MainForm.cs#L491

into following location:

https://github.com/stax76/mpv.net/blob/master/mpv.net/WinForms/MainForm.cs#L348

I cannot promise that it fixes it but it's a try. I've never had this issue but sometimes (every other day) I have something similar: title bar disappears.

mpv.net doesn't show the osc, libmpv handles this self, only thing mpv.net does is sending the mouse command:

https://mpv.io/manual/master/#command-interface-mouse-%3Cx%3E-%3Cy%3E-[%3Cbutton%3E-[single|double]]

**Comment by TETYYS** [comment] 2019-06-18 22:45
Still happens, but only with audio files

**Comment by stax76** [comment] 2019-06-26 01:38
Does it happen when you toggle fullscreen via key or does it happen when you toggle fullscreen via double-click?

This could be a bug in windows, in the GPU driver or in mpv rendering, you could try `vo = direct3d` to confirm this theory. You could also try if it also happens with mpv.

What are your system specs? Mine are:

Win 10 1903
NVIDIA GT 1030

**Comment by TETYYS** [comment] 2019-06-26 08:41
Happens when double clicking and with hotkey. Switching from `vo=gpu` to `vo=direct3d` seems to be fixing the issue.

Win 10 1809
Inter HD Graphics 520

**Comment by 44vince44** [comment] 2019-06-26 19:39
Tettyys, if i recall, direct3d does not take into account color matrixes, which results in some movies playing with slightly bad colors (like a hue problem). Try this:
vo=gpu
hwdec=no

I am also on a Intel HD setup, and disabling hardware decoding fixed the problems.

**Comment by stax76** [comment] 2019-06-26 20:19
`vo = gpu` is redundant though as it's the default.

my full specs:

Win 10 1903
NVIDIA GT 1030

**profile = gpu-hq**
input-ar-delay = 500
input-ar-rate = 20
volume = 50
keep-open = always
keep-open-pause = no
screenshot-directory = '~~desktop/'
input-default-bindings = no
screen = 1
osd-playing-msg = '${filename}'
alang = 'de,en'
**hwdec = yes**

**Comment by 44vince44** [comment] 2019-06-26 20:35
try hwdec=no and i bet the osc problem will be gone!

**Comment by TETYYS** [comment] 2019-06-26 20:39
Problem still persists with `hwdec=no` and `vo=gpu`

**Comment by 44vince44** [comment] 2019-06-26 20:43
Oh I see... Problem is that I couldn't reproduce it here...

**Comment by bitsper2nd** [comment] 2020-05-10 22:52
I never had this problem when I use mpv.net on full screen. I have a suggestion, it does not fix the issue, but nonetheless solves your problem. have you tried using an alternative osc like [darsain uosc](https://github.com/darsain/uosc) or [rjno1 osc styles](https://github.com/422658476/MPV-EASY-Player)?

**Comment by stax76** [comment] 2020-05-11 10:12
I think there was a fix, so I'm closing it.

**Closed by stax76** 2020-05-11 10:12 UTC
Labels: not reproducible
