### ISSUE TITLE
Remember window side for all sessions

### ISSUE THREAD

**Issue by TheBestPessimist** [stax76/mpv.net#140] opened 2020-03-23 06:31 UTC
Followup of https://github.com/stax76/mpv.net/issues/133.

Currently remembering the window size is supported only in the current session (previous/next video).

I would like to have the window size remembered for all the sessions.

Background: I always keep the window on the half-right side of the screen (ie. "snapped right" by drag and drop of the titlebar), and each time i close mpv.net, when it is re-opened, it starts on an _apparently random_ position on the screen instead of starting on the right side as i set it up.

An example of my usecase is found in https://github.com/stax76/mpv.net/issues/140#issuecomment-617555293

**Comment by stax76** [comment] 2020-04-19 19:09
New beta version is now available:

https://github.com/stax76/mpv.net#beta

**Comment by TheBestPessimist** [comment] 2020-04-21 11:07
I tested with the beta 5.4.4.3, but the size is not remembered. 
what settings to i need to change besides `start-size: always`?

**Comment by stax76** [comment] 2020-04-21 12:51
Only start-size=always, but it's mpv.net specific, it must be in mpvnet.conf and not in mpv.conf.

**Comment by TheBestPessimist** [comment] 2020-04-21 17:12
I set it here, and never edited any config file manually: 
![image](https://user-images.githubusercontent.com/4482210/79893210-65c36680-840c-11ea-8452-c3582e0aac39.png)

**Comment by stax76** [comment] 2020-04-22 04:52
Unfortunately I'm not able to reproduce it.

**Comment by TheBestPessimist** [comment] 2020-04-22 05:14
1. Open mvp.net. mine is by default in borderless
2. Press `b` to enable borders
3. Drag the mpn.net window to the right side of the screen (right screen snap) so that mpv.net occupies half of the screen
4. Restart mpv.net

expected: 
1. mpv.net remains in bordered mode (since i toggled that just now)
2. mpv.net remembers the window position "right snapped"

actual:
1. :x: mpv.net starts in borderless mode
2. :x: mpv.net starts in the middle of the screen

Here's a gif showing that
![0000001373](https://user-images.githubusercontent.com/4482210/79943353-54607580-8471-11ea-8436-92d65236dca1.gif)

**Comment by stax76** [comment] 2020-04-22 05:30
OK, I understand now.

**Comment by stax76** [comment] 2020-04-22 07:40
For now, I mark this as _won't fix_ as it's far too specialized for spending hours on it, it may look simple to do but it's not.

**Comment by TheBestPessimist** [comment] 2020-04-22 09:06
In that case: is there a way to resize the window without respecting the ratio?

Right now resizing works as follows: i click the bottom of the window and drag the mouse down. The problem is that the width of the window is increased as well (so as to maintain a specific aspect ratio).

What i want is to manually be able to resize the window to half screen size, and move it there. That would be a good workaround.

**Comment by stax76** [comment] 2021-05-29 11:02
Please try the last release.

**Comment by TheBestPessimist** [comment] 2021-06-11 05:59
Remembering autostart size does not work.




https://user-images.githubusercontent.com/4482210/121637776-98a63f00-ca92-11eb-9b37-c28d861f1e02.mp4

**Comment by stax76** [comment] 2021-06-17 14:37
Sorry there was a bug, it will be fixed in the next release, thank you for testing.

**Comment by TheBestPessimist** [comment] 2021-06-18 05:31
Size is fixed (i cannot test as there is no beta release yet) and that's nice.
What about "remembering the side of the screen where mpv was". Is `SaveWindowProperties()` doing that as well?

**Comment by stax76** [comment] 2021-06-18 05:58
> What about "remembering the side of the screen where mpv was". Is SaveWindowProperties() doing that as well?

Yes it does.

**Comment by stax76** [comment] 2021-06-23 06:05
There is a new beta version addressing this issue.

**Closed by stax76** 2021-06-23 06:05 UTC
Labels: bug, feature request, fixed/added
