### ISSUE TITLE
mpv.net crashes when I use vapoursynth scripts for motion interpolation 

### ISSUE THREAD

**Issue by computator1200** [stax76/mpv.net#374] opened 2022-03-03 06:24 UTC
I'm using windows 10.0.19043.1526 and the microsoft store version of mpv.net

I have vapoursynth and the mvtools library installed but when I added the following lines to my mpv conf: 

`vf=vapoursynth="C:\Users\NEW ASPIRE 7\Documents\motioninterpolation.vpy":buffered-frames=4:concurrent-frames=32`
`[extension.vpy]`
`demuxer-lavf-format = vapoursynth`

and launched mpv.net, it shows a black screen for a few seconds then crashes. I tried it with normal mpv and it worked fine. How can this be fixed?

I tried installing the mpv.net exe, the one for program files and it worked in that, if it's only a problem with the microsoft store version, can you fix that?

**Comment by computator1200** [comment] 2022-03-03 18:22
> What is the content of the vpy file?

[this](https://gist.github.com/phiresky/4bfcfbbd05b3c2ed8645#file-motioninterpolation-vpy)

**Comment by stax76** [comment] 2022-03-04 14:06
You mean log you created yourself? Is there maybe a mpv property allowing to define the Python path? In case default DLL loading is used, it would work adding Python to PATH because default DLL loading utilizes PATH. Default DLL loading means the way Windows searches DLLs.

I tried with mpv using a recent zhongfly build and here it exits without doing anything, not even writing an error to the console.

I tried both:

core = vapoursynth.get_core()
core = vapoursynth.core

Python 3.10 is installed and in PATH.

**Comment by hooke007** [comment] 2022-03-04 18:49
> You mean log you created yourself?

yes

> Is there maybe a mpv property allowing to define the Python path?

nope

> Python 3.10

official r57 only support py3.8 or 3.9

**Comment by stax76** [comment] 2022-03-05 02:25
I think my issue was not having vapoursynth installed or in PATH. I downloaded the last staxrip release and added its portable Python/VapourSynth folder at the top of PATH, then it worked with both mpv and mpv.net, so it's generally working with a recent zhongfly built using mpv.net, I close it since it cannot be reproduced.

**Closed by stax76** 2022-03-05 02:25 UTC
Labels: bug, not reproducible, priority high

**Comment by hooke007** [comment] 2022-03-05 03:24
> From the log it seemed that it (microsoft store version) didn't find the python.

I copied the all the files into another place. And then everything works well. There probably some limits in `C:\Program Files\WindowsApps\` folder.

**Comment by computator1200** [comment] 2022-03-05 10:55
how exactly do you fix it?

**Comment by computator1200** [comment] 2022-03-05 10:55
> > From the log it seemed that it (microsoft store version) didn't find the python.
> 
> I copied the all the files into another place. And then everything works well. There probably some limits in `C:\Program Files\WindowsApps\` folder.

where did you copy the files to @hooke007

**Comment by hooke007** [comment] 2022-03-05 12:19
Any directory which doesn't need UAC.

**Comment by computator1200** [comment] 2022-03-05 12:21
> Any directory which doesn't need UAC.

which files should I copy

**Comment by hooke007** [comment] 2022-03-05 12:28
I don't fix the problem.
I mean the store's mpvnet was installed in the directory that PATH cannot access. So just move all the files (the store installed) to another place to avoid the problem.

> which files

A folder named `mpv.net`

**Comment by computator1200** [comment] 2022-03-05 12:30
> I don't fix the problem. I mean the store's mpvnet was installed in the directory that PATH cannot access. So just move all the files (the store installed) to another place to avoid the problem.
> 
> > which files
> 
> A folder named `mpv.net`

you mean the WindowsApps directory?

**Comment by computator1200** [comment] 2022-03-05 12:30
> I don't fix the problem. I mean the store's mpvnet was installed in the directory that PATH cannot access. So just move all the files (the store installed) to another place to avoid the problem.
> 
> > which files
> 
> A folder named `mpv.net`

what is PATH

**Comment by hooke007** [comment] 2022-03-05 12:37
...From my view, using the github's portable version is the best resolution.

**Comment by computator1200** [comment] 2022-03-05 12:41
> ...From my view, using the github's portable version is the best resolution.

yeah but in the microsoft store version the context menu has rounded edges, is there a way to get that in the github releases?

**Comment by hooke007** [comment] 2022-03-05 12:51
https://github.com/stax76/mpv.net/issues/375#issuecomment-1059701664

**Comment by computator1200** [comment] 2022-03-05 13:10
> I don't fix the problem. I mean the store's mpvnet was installed in the directory that PATH cannot access. So just move all the files (the store installed) to another place to avoid the problem.
> 
> > which files
> 
> A folder named `mpv.net`

I copied the mpv.net folder from WindowsApps to my program files and it works from there, what happens if I uninstall the mpv.net from the microsoft store now?

**Comment by hooke007** [comment] 2022-03-05 14:45
WindowsApp‘s mpvnet would be uninstalled.

**Comment by computator1200** [comment] 2022-03-06 08:21
> WindowsApp‘s mpvnet would be uninstalled.

will it affect the one I copied?

**Comment by stax76** [comment] 2022-05-25 15:08
There is now a guide in the wiki:

https://github.com/stax76/mpv.net/wiki/Using-VapourSynth-in-mpv.net
