### ISSUE TITLE
Retain the pre-fullscreen window size after exiting fullscreen

### ISSUE THREAD

**Issue by tarantinosaur** [stax76/mpv.net#149] opened 2020-04-17 13:17 UTC
Right now, the window becomes smaller when you exit from fullscreen.

**Comment by stax76** [comment] 2020-04-18 14:18
If I understand right then the issue is going from maximized to full screen goes not back to maximized after leaving full screen.

**Comment by tarantinosaur** [comment] 2020-04-18 14:33
Yeah, that's what I meant. Sorry for the poor phrasing.

**Comment by stax76** [comment] 2020-04-18 15:48
No problem, I hope I can fix it but it's not high priority, related code was sometimes tricky in the past, we'll see.

**Comment by stax76** [comment] 2020-04-19 18:09
I've added this now. When it's online I'll post here and close it.

**Comment by stax76** [comment] 2020-04-19 19:08
New beta version is now available:

https://github.com/stax76/mpv.net#beta

**Closed by stax76** 2020-04-19 19:08 UTC
Labels: addressed in next release
