### ISSUE TITLE
Cannot launch from secondary monitor.

### ISSUE THREAD

**Issue by User-3090** [stax76/mpv.net#397] opened 2022-04-01 16:35 UTC
Cannot launch mpvnet by clicking a file if file manager / explorer is located on secondary monitor. Nothing happens. No windows opens. I'm sort of guessing this might have to do with color management. Both screens have ICC profiles assigned. 

Config:

# Editor
vo=gpu-next
icc-profile-auto
vf=format=colormatrix=bt.709
vf=format=primaries=bt.709

Win10, RTX 3090, 472.xx Nvidia driver.

**Comment by stax76** [comment] 2022-04-01 17:39
With default settings, it's not reproducible, you can try starting from a console and check if errors are printed on the console.

**Comment by ghuser123321** [comment] 2022-04-01 18:51
Revert to default config and some thing. Also happens when launching from cmd.exe. if cmd.exe is on primary screen it launches fine, if on second screen I get this trace:

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at libmpv.mpv_command(IntPtr mpvHandle, IntPtr strings)
   at mpvnet.CorePlayer.CommandV(String[] args)
   at mpvnet.CorePlayer.ShowLogo()
   at mpvnet.MainForm.OnResize(EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmCreate(Message& m)
   at mpvnet.MainForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by stax76** [comment] 2022-04-02 09:09
I'm not able to reproduce it, but probably can work around it.

**Comment by stax76** [comment] 2022-04-03 16:16
You can now try the new beta version, it should handle this issue.

**Comment by ghuser123321** [comment] 2022-04-04 10:44
Unfortunately the beta doesn't fix it. The trace print is gone. Now no output to terminal at all. Is there any flag for more verbose logging? Thanks for all your time and efforts in this project!

**Comment by stax76** [comment] 2022-04-08 18:01
Sorry about the delay, I was working on another issue.

You can generate a log file:

https://mpv.io/manual/master/#options-log-file

If you use mpv instead of mpv.net, does that work?

**Comment by ghuser123321** [comment] 2022-04-12 11:30
Sorry for the delay:
* Plain mpv (not mpv.net) works fine.
* It crashes before even creating the a log file
* Setting the screen to landscape orientation doesn't change anything
* -vvv at least gives me the following trace:
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at libmpv.mpv_command(IntPtr mpvHandle, IntPtr strings)
   at mpvnet.CorePlayer.CommandV(String[] args) in D:\Projects\CS\mpv.net\src\Misc\CorePlayer.cs:line 708
   at mpvnet.CorePlayer.ShowLogo() in D:\Projects\CS\mpv.net\src\Misc\CorePlayer.cs:line 1358
   at mpvnet.MainForm.OnResize(EventArgs e) in D:\Projects\CS\mpv.net\src\Misc\MainForm.cs:line 1075
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmCreate(Message& m)
   at mpvnet.MainForm.WndProc(Message& m) in D:\Projects\CS\mpv.net\src\Misc\MainForm.cs:line 924
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by stax76** [comment] 2022-04-14 11:03
To try if the problem is caused by an option, the command line option `--config=no` can be used (same as with original mpv).

If that does not work, I so far have nothing which can provide a hint on how to reproduce the problem, which typically means there is nothing I can do until a way is found to reproduce the issue.

AccessViolationException typically means the problem happens in native code, in libmpv, it's possible that it exists in mpv too but goes unnoticed because there is no .NET Runtime that detects it.

Do you see `<LogoCrash>true</LogoCrash>` in settings.xml? It means the code has crashed in the ShowLogo routine, it then does not execute the routine a second time. It's also possible to disable the logo drawing by putting `show-logo = no` in mpvnet.conf. If it's not solving the problem, it means the problem lies deeper.

**Comment by ghuser123321** [comment] 2022-04-14 11:26
`<LogoCrash>false</LogoCrash>` and `show-logo = no` makes no difference. It's been ages since I did .NET development, but I'll try to clone the repo and see what I can figure out when I have a bit of time.

Can't I use [ProcDump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) to get a dump and view in WinDBG? I forget all the flags. If you are using that for development, do have a cmd line I could try? Once I have dump I can probably get around in WinDBG.

**Comment by ghuser123321** [comment] 2022-04-14 11:32
Okay, I figured out what is causing the crash is:

Screen 1 is set 125% scaling in windows
Screen 2 is set to 100% scaling in windows

in that config it crashes when launched from screen 2

when setting screen 2 also to 125% scaling it works fine!

**Comment by stax76** [comment] 2022-04-14 12:13
You found it. I'll try to fix it, but might need some days.

**Comment by stax76** [comment] 2022-04-17 09:59
I can reproduce it now!

**Comment by stax76** [comment] 2022-04-28 14:58
My error handing was faulty, in the last beta you can change the option:

UI > show-logo

Disabling it should prevent the issue.

**Comment by stax76** [comment] 2022-04-28 19:55
I found the problem now, it will be fixed in the next release.

**Comment by User-3090** [comment] 2022-04-30 15:59
Thanks, can't wait for a new release to test. I haven't seen a donation button anywhere. If it does exist, appreciate if you could point me to it :)

**Comment by stax76** [comment] 2022-05-01 11:06
Thanks considering a donation, which you can do here:

https://ko-fi.com/stax76

Here is a hotfix:

[mpvnet.zip](https://github.com/stax76/mpv.net/files/8598753/mpvnet.zip)

**Closed by stax76** 2022-05-01 11:06 UTC
Labels: bug, fixed/added, priority high
