### ISSUE TITLE
XML error

### ISSUE THREAD

**Issue by AliNemati13** [stax76/mpv.net#281] opened 2021-07-07 16:06 UTC
**Describe the bug**
Can't start the program, mpv was okay until the next day when i wanted to open the app

**Screenshots**
![1](https://user-images.githubusercontent.com/37639464/124793082-e3688900-df62-11eb-91f1-d5741a88abea.png)
![2](https://user-images.githubusercontent.com/37639464/124793102-e794a680-df62-11eb-81a2-a6f67755fec4.png)

**Additional context**
[Detail.txt](https://github.com/stax76/mpv.net/files/6778656/Detail.txt)

**Comment by anymeofu** [comment] 2021-07-15 02:49
Same Error for me too !

**Comment by vH000v** [comment] 2021-07-16 00:06
I also encountered this error.
Im not sure of the root cause however when it occured the settings.xml was cleared.

To temporarily fix the issue I deleted the empty settings.xml

**Comment by AliNemati13** [comment] 2021-07-16 19:37
> I also encountered this error.
> Im not sure of the root cause however when it occured the settings.xml was cleared.
> 
> To temporarily fix the issue I deleted the empty settings.xml

where is this settings.xml file ? i can't find it

**Comment by vH000v** [comment] 2021-07-16 19:41
> where is this settings.xml file ? i can't find it

You can find it in the [https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#settings](settings folder)

> startup\portable_config
> %APPDATA%\mpv.net

**Comment by stax76** [comment] 2021-07-17 14:18
Is anybody of you using multiple mpv.net instances in parallel (`process-instance=multi`)?

**Comment by stax76** [comment] 2022-03-05 14:46
It should be fixed in the last beta:

https://github.com/stax76/mpv.net/releases

**Closed by stax76** 2022-03-05 14:46 UTC
Labels: bug, fixed/added, priority medium
