### ISSUE TITLE
Rotated video is grayscaled

### ISSUE THREAD

**Issue by idnsunset** [stax76/mpv.net#388] opened 2022-03-15 18:51 UTC
**Describe the bug**
90-degree Rotated video is grayscaled with streaks.

**To Reproduce**
1. Play a video
2. Press `Ctrl`+`r`

**Expected behavior**
Video is displayed as normal.

**Additional context**
#193 reported the same issue, but why was it closed without fix?

**Comment by hooke007** [comment] 2022-03-15 20:53
It's totally upstream's issue. Nothing we could do here. https://github.com/mpv-player/mpv/issues/8223

**Comment by mdmjmsa** [comment] 2022-03-19 11:34
> It's totally upstream's issue. Nothing we could do here. [mpv-player/mpv#8223](https://github.com/mpv-player/mpv/issues/8223)

What mpv version does mpv.net depends on? The mpv 0.34 stable release has no such issue.

**Comment by hooke007** [comment] 2022-03-19 12:53
I have no idea why you cannot reproduce it. It was never fixed in `vo=gpu` since 0.32 git

![Snipaste_2022-03-19_12-51-12](https://user-images.githubusercontent.com/41094733/159121874-3fa98299-0e81-4f4e-9607-4417edd48b90.jpg)

**Comment by mdmjmsa** [comment] 2022-03-19 15:34
```
mpv 0.34.0 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on Sun Nov  7 20:16:38 +08 2021
FFmpeg library versions:
   libavutil       57.7.100
   libavcodec      59.12.100
   libavformat     59.8.100
   libswscale      6.1.100
   libavfilter     8.16.101
   libswresample   4.0.100
FFmpeg version: git-2021-11-06-1728127e

Usage:   mpv [options] [url|path/]filename

Basic options:
 --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
 --no-audio        do not play sound
 --no-video        do not play video
 --fs              fullscreen playback
 --sub-file=<file> specify subtitle file to use
 --playlist=<file> specify playlist file

 --list-options    list all mpv options
 --h=<string>      print options which contain the given string in their name

F:\Videos\adlt>"F:\tmp\mpv.com" --hwdec=yes --video-rotate=90 \\MAD-T410\Videos\tech\cmu02.mp4
 (+) Video --vid=1 (h264 1280x720 29.970fps)
 (+) Audio --aid=1 (aac 2ch 48000Hz)
Cannot load nvcuda.dll
Using hardware decoding (d3d11va).
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 1280x720 d3d11[nv12]
(Paused) AV: 00:00:02 / 01:11:04 (0%) A-V:  0.000 Cache: 369s/88MB
```
![mpv-cmu02-90degree](https://user-images.githubusercontent.com/101821487/159127592-9513dbec-0c5d-410b-abd5-7eebc97038ec.png)

**Comment by hooke007** [comment] 2022-03-19 15:38
You don't review the issue I mentioned. It's clear that `cscale=bilinear` would not reproduce the bug.

**Comment by mdmjmsa** [comment] 2022-03-19 15:44
> You don't review the issue I mentioned. It's clear that `cscale=bilinear` would not reproduce the bug.
> 
> [mpv-player/mpv#8223 (comment)](https://github.com/mpv-player/mpv/issues/8223#issuecomment-781062456)

Got it, thank you!

**Closed** 2022-05-08 13:30 UTC
Labels: bug, priority low, not an issue, upstream
