### ISSUE TITLE
Playlist/Auto-Play broken on 2nd screen 

### ISSUE THREAD

**Issue by ll811** [stax76/mpv.net#161] opened 2020-05-06 06:39 UTC
**Auto-play is broken when dragging the player over to my television screen. Once a file is finished playing and the next one in the playlist starts, the player exits full screen mode and removes the border of the player.**

**To Reproduce**
1. Drag player over to 2nd "extended" display
2. Start any playlist 
3. Skip to next file in playlist

**Player will exit full screen and border will disappear**

**Comment by stax76** [comment] 2020-05-06 12:51
Maybe a driver bug, what's in your mpv.conf?

**Comment by ll811** [comment] 2020-05-06 14:29
> Maybe a driver bug, what's in your mpv.conf and which OS and gx card?

Windows 10 and GTX 960. Running the latest version of mpvnet 

input-ar-delay = 500
input-ar-rate = 20
volume = 85
volume-max = 100
hwdec = yes
keep-open-pause = no
osd-playing-msg = '${filename}'
screenshot-directory = 'E:\mpvscreenshots'
input-default-bindings = no
scale = spline36
cscale = spline36
dscale = mitchell
correct-downscaling = yes
linear-downscaling = yes
sigmoid-upscaling = yes
dither-depth = auto
deband = yes
autofit-larger = 100
autofit-smaller = 40
sub-font-size = 45
sub-border-size = 2
screenshot-template = '%F %P'
screenshot-jpeg-quality = 98
script-opts = osc-vidscale=no
taskbar-progress = no
slang = 'English,eng,en'
alang = 'English,eng,en'
screenshot-png-compression = 7
# Editor

and mpvnet.config

start-size = video
minimum-aspect-ratio = 0
recent-count = 0
url-whitelist = '******************'
# Editor
remember-volume = no

**Comment by 44vince44** [comment] 2020-05-06 17:06
@ll811 , I tested on my setup, extended display, did the operation as you describe, and it was flawless. I had absolutely no problem!
You should backup your conf files (input.conf , mpv.conf and mpvnet.conf) in an archive, delete them, and try to see if the problem occurs with the default configs...

**Comment by ll811** [comment] 2020-05-06 17:21
>@44vince44 @stax76  
>1. You should backup your conf files (input.conf , mpv.conf and mpvnet.conf) in an archive, delete them, and try to see if the problem occurs with the default configs...
> 2. you could also try this modification in mpv.net :
>    delete line hwdec=yes
>    put instead:
>    vo=gpu,
>    hwdec=no
>    copy exactly as is, the comma " , " after "gpu" is intended, you must keep it.
> 
> Please try and tell me what happens.

I figured out what it was. It is the mpvnet.config 

start-size = video

Using "Window set to Video Resolution" setting is what causes it. Again, this is only on the extended display. I tested this having deleted both config files and starting fresh with nothing but start-size = video and the problem still occurred. 

HOWEVER, the problem only seems to occur if the files you're jumping between have a different resolution.

**Comment by ll811** [comment] 2020-05-06 17:37
> 2. you could also try this modification in mpv.net :
>    delete line hwdec=yes
>    put instead:
>    vo=gpu,
>    hwdec=no
>    copy exactly as is, the comma " , " after "gpu" is intended, you must keep it.

Sorry if this is a stupid question. But in mpv.config or in mpvnet.config?

**Comment by 44vince44** [comment] 2020-05-06 18:07
OK so you found out that:

when     start-size = video
AND      using 2nd display in EXTENDED mode
AND      video size = 1080p same as 2nd display size

THEN navigate from a file to next file takes you away from fullscreen and removes borders.

@stax76 is it possible that mpvnet is reading screen dimensions the sum of the two displays?

**Comment by ll811** [comment] 2020-05-06 18:21
> @ll811 can you please try one last thing: in mpvnet.conf, under start-size=video, put this line:
> start-threshold = 2000

Tried it, didn't change anything.

**Comment by 44vince44** [comment] 2020-05-07 03:42
Ok, thanks for testing. I guess Stax should take a look at that. In the mean time, obviously you can remove "start-size = video" from mpvnet.conf and set "autofit=65%" in mpv.conf. This works fine.

**Comment by ll811** [comment] 2020-05-07 15:13
Also, I don't know if this information is relevant, but my main monitor is 1440p, and the 2nd extended screen is 1080p.

**Comment by 44vince44** [comment] 2020-05-08 13:03
@ll811 did you test latest betas from the beta dropbox ? there has been a change in the handling of messages, maybe it's fixed.
Also note that if you're using old config files or customized from some time ago, you should open the console and see at startup if there are errors, so you can remove the commands causing errors. I had a problem that seemed unrelated and it was fixed by cleaning up the conf files. If you didn't customize them, just delete them and let the new mpv.net create proper ones.

**Comment by ll811** [comment] 2020-05-08 14:38
@44vince44 seems unlikely that it has anything to do with the config files since I tried deleting them earlier and then doing nothing but adding "start-size = video" in mpvnet.config and had the same issue. 

5.4.5.0 changed something with regards to how mpv handles video size / resolution (ironically enough after an issue I had reported on with black bars on certain media) maybe that has something to do with this new error?

This issue was introduced with 5.4.5.0, version prior to that things worked as normal. Just to make absolute sure I went back and tested them, I tested 5.4.4.0 and the 3 releases that came after, 5.4.4.0 works as it should and the others are broken.

I appreciate how helpful you are. Also, I did not try the beta.

**Comment by stax76** [comment] 2020-05-09 00:46
@ll811 

Both 44vince44 and me are not able to reproduce it. There are only 2 functions that change windows size and window state. There's a function that cycles fullscreen and it's triggered when the mpv property `fullscreen `changes which shouldn't change in this case and there is another function that handles all the rest, this function is however not entered in fullscreen mode, this function checks in the beginning if the window is minimized or maximized and if so the function is exited.

Do you run any user scripts?

Adding some logging code is the only idea I have.

**Comment by ll811** [comment] 2020-05-09 01:10
@stax76 I have tried with the portable versions of the past 4 releases with the config files removed each time before a test. It is broken on all of them but 5.4.4.0. But I noticed just now that the issue goes away if I lower the resolution on my tv to 720p. 

Truly bizarre. Also no user scripts.

**Comment by ll811** [comment] 2020-05-09 01:19
@stax76 okay I just found a "fix" to this issue. If I scale the window down before dragging mpvnet over to my extended screen, switching between files in the playlist works as it should. It is when I drag the full window over to the display that it breaks when switching between files.

**Comment by stax76** [comment] 2020-05-09 01:46
What does full window mean? Was it maximized or was it full screen or was it normal + filling the complete working area?

**Comment by ll811** [comment] 2020-05-09 02:15
@stax76 full window (frame of mpv and video) into full screen. With "start-size = video" the frame of mpv is dependent on resolution of the file as you know, and this issue only occurs on 1080p files on my tv. If I scale the 1080p frame down manually BEFORE I go full screen on the tv, swapping between files won't break the window.

**Comment by stax76** [comment] 2020-05-09 02:38
Please make screenshots.

**Closed** 2020-05-09 06:40 UTC
Labels: info needed, not reproducible

**Comment by ll811** [comment] 2020-05-09 10:07
@stax76 I did the best I could with the screenshots. 

![1](https://user-images.githubusercontent.com/54498049/81470766-dcbe7480-91ec-11ea-9325-03ad8b291b38.jpg)
![2](https://user-images.githubusercontent.com/54498049/81470768-ddefa180-91ec-11ea-8751-209a70daaa5a.jpg)
![3](https://user-images.githubusercontent.com/54498049/81470769-ddefa180-91ec-11ea-9982-330c6059a900.jpg)
![4](https://user-images.githubusercontent.com/54498049/81470770-de883800-91ec-11ea-9cdb-f85278214d71.jpg)
![5](https://user-images.githubusercontent.com/54498049/81470771-de883800-91ec-11ea-856a-e8d9d941b89f.jpg)
![6](https://user-images.githubusercontent.com/54498049/81470772-de883800-91ec-11ea-9fd4-c999e7841449.jpg)

Something I've yet to mention is that when mpvnet exits full screen, to get the border back I have to double click the player 2 times and it will snap back into full screen and give the border back. Alternatively click B two times.

**Comment by stax76** [comment] 2020-05-09 15:24
I did my best trying to reproduce this, unfortunately I cannot.

**Comment by stax76** [comment] 2020-05-09 15:30
Maybe use `screen = 1` to start directly on TV, that's my config.

**Comment by ll811** [comment] 2020-05-09 16:00
> I did my best trying to reproduce this, unfortunately I cannot.

That's unfortunate. Thanks for trying, though. You have absolutely no clue as to what it may be given that it occurred between 5.4.4.0 and 5.4.5.0? You did change something with how mpvnet interprets video size / resolution between those two, right? I guess it's not possible to fix something when you can't reproduce the error yourself.

**Comment by ll811** [comment] 2020-05-09 16:08
mpvnet is acting strange on me in general it seems, now I'm getting inconsistencies in start-size = video as well, a 1080p one will be downscaled to 720p, then restarting the player/file and it'll be its full 1080p self again.

Maybe I should just remove it and do a clean install. Are any config settings saved outside of "AppData\Roaming\mpv.net" ?

**Comment by 44vince44** [comment] 2020-05-09 16:40
@ ll811 This is strange. I will test all those things a bit later:
- uninstall
- issue on extended desktop and try to reproduce it

**Comment by 44vince44** [comment] 2020-05-09 16:50
uninstall : tested twice, worked flawlessly !

**Comment by ll811** [comment] 2020-05-09 16:54
> uninstall : tested twice, worked flawlessly !

I ended up deleting the files manually, as well as cleaning up the appdata folder, and restarting the computer before a fresh install. Still have the same issue on the extended display after having changed nothing but the "Start-size = video" setting.

**Comment by 44vince44** [comment] 2020-05-09 17:47
@ll811 @stax76 I confirm the issue of the second display in "Extend". 
My display1 = 1920x1080, my display2 = 1280x720 
In order to reproduce it:

1. Put **Start-size = video in mpvnet.conf**
2. connect the second display, configure desktop to EXTEND mode
3. open mpv.net on the display1, load a bunch of files that must have **exact resolution as display2**
4. drag mpv.net to display2, DO NOT RESIZE, play
5. put in full screen ( = double-click in the middle of mpv.net)
5. jump to next file

=> when it jumps to next file, mpv.net quits full screen mode, and has no borders !!!

It seems that when draging mpvnet from display1 to display2, there is some information missing, no? Because in step 4, if you RESIZE the window just before going to full screen, the problem doesn't happen.

@ll811 This could be something difficult to track and to fix. I really suggest you remove start-size=video, 
Removing start-size=video, and setting autofit=65% is, in my opinion, far better for regular the operation of mpv.net.
And one day Stax will "accidentally" fix it ...

**Comment by ll811** [comment] 2020-05-09 18:07
@44vince44 Wow, thank you for going through the trouble! Glad someone was at least able to reproduce the issue. Thank you for the suggestion, I'll use that for now! 

Is it possible to bind window size to a key? Say I open a 480p file, using autofit=65 is going to upscale this a great deal, say I wanna bind "z" to scale the window to the size of the original resolution, is that possible?

**Comment by 44vince44** [comment] 2020-05-10 09:15
@ll811 there is no such binding, there is a command window-scale but it scales to the size of the current window.

You are trying to achieve 1 pixel of the display = 1 pixel of the video. Exact pixel match.
Is it for forensic purpose? (lol) or just eye comfort?
You can get optimal results by choosing a proper resizing algorithm. 
Drop these lines in your mpv.conf:
scale = ewa_lanczossharp
cscale = ewa_lanczossharp
dscale = ewa_lanczossharp
If your hardware can handle it (a three year old hardware can do it easily, but for 4K content you need more recent), you'll forget anything bout exact piixel.

And don't forget, Stax will stumble on it one day.

**Comment by ll811** [comment] 2020-05-10 09:56
@44vince44 It's more that I sometimes want to view a video at its native resolution. I've got like a 7 year old cpu and the gtx 960, think it'll handle that setup well?

**Comment by 44vince44** [comment] 2020-05-10 10:52
@ll811 gtx 960 should handle it... (you can check the gpu activity in windows task manager while playing)

**Comment by ll811** [comment] 2020-05-10 11:50
@44vince44 @stax76 
![black border](https://user-images.githubusercontent.com/54498049/81498420-2aa6ab80-92c5-11ea-8a70-2dde4e847f1f.jpg)
Feels like I'm just being a nuisance now, but 65% autofit on 1080p creates this black line on both sides of the player that isn't there at native resolution.

**Comment by 44vince44** [comment] 2020-05-10 12:24
@ll811 what is the resolution of the video file exactly?

**Comment by ll811** [comment] 2020-05-10 12:26
@44vince44 1920x1080 using 65% autofit.

**Comment by 44vince44** [comment] 2020-05-10 12:32
???? send me a mediainfo please to check AR etc....

**Comment by ll811** [comment] 2020-05-10 12:41
@44vince44 It's there 'on all 1080p files, it's not just this one. 
![mpvblack](https://user-images.githubusercontent.com/54498049/81499452-16b27800-92cc-11ea-8268-3e720d66db39.jpg)
> what does that mean ?

Native resolution / Native scale. 1080p at 65 autofit is downscaled slightly from 1080p, the window at it's native size does not have the black lines on the sides.
![mpvnoblackline](https://user-images.githubusercontent.com/54498049/81499454-174b0e80-92cc-11ea-8637-106ddd8c568e.jpg)

**Comment by 44vince44** [comment] 2020-05-10 12:51
so now show me the side bars with this same file

**Comment by ll811** [comment] 2020-05-10 13:03
@44vince44 it's already visible in the two screenshots I posted above. Bottom one has no black line on the right side, top one does.
![autofit](https://user-images.githubusercontent.com/54498049/81499972-60e92880-92cf-11ea-8fa8-fb01d52b5439.jpg)

**Comment by 44vince44** [comment] 2020-05-10 13:05
OMG you mean black tiny lines of ONE PIXEL width ? LOL, never noticed them.

**Comment by ll811** [comment] 2020-05-10 13:05
@44vince44 
> OMG you mean black tiny lines of ONE PIXEL width ? LOL, never noticed them.

lmao, yes.

**Comment by 44vince44** [comment] 2020-05-10 13:05
Ok those will be treated in another thread. A little bit later I'll post it (but before, I need to check several things)

**Comment by 44vince44** [comment] 2020-05-10 13:40
@ll811 
This is a border issue, my display is 1080p, i took a full 1080p video and set autofit=65% (i hope you haven't forgotten to put the %".
I get a normal result! Of course I'mdoing this on the primary display.
![Untitled-1](https://user-images.githubusercontent.com/17828567/81500775-02c34200-92dd-11ea-92c1-e41c6dfa08b6.jpg)

**Comment by 44vince44** [comment] 2020-05-10 13:41
So it is normal !!!!!

**Comment by ll811** [comment] 2020-05-10 13:55
@44vince44 You're looking at the wrong side, the black pixel line appears on the right side, not the left. I still see it when hiding the border. 
>I hope you haven't forgotten to put the %

Does that matter? I had just put 65 in the settings, I changed to 65% and I haven't noticed anything different.

**Comment by 44vince44** [comment] 2020-05-10 14:17
OK i confirm it's there, only in the case of 1920x1080 video.
On my first test it was a 1920x800 video (anamorphic cinema).
It doesn't happen with original mpv. I'll open a new thread

**Comment by ll811** [comment] 2020-05-10 14:21
@44vince44 thank you

**Comment by 44vince44** [comment] 2020-05-10 14:42
you're welcome. let's hope that stax will take a look at it
