### ISSUE TITLE
error sound when closing from taskbar

### ISSUE THREAD

**Issue by scattass** [stax76/mpv.net#98] opened 2019-09-21 03:56 UTC
not a big deal but kind of annoying. doesn't make a sound when closing from exiting application. maybe its just my machine. where is the log so I can check it?

**Comment by stax76** [comment] 2019-10-04 15:38
It was caused by an exception, new release is coming soon. Thanks for reporting.

**Comment by stax76** [comment] 2019-10-13 04:18
Hi, it's fixed in the built released today.

**Closed by stax76** 2019-10-13 04:18 UTC
