### ISSUE TITLE
No gradual volume increment on keyboard volume knob.

### ISSUE THREAD

**Issue by AE720** [stax76/mpv.net#143] opened 2020-04-01 18:04 UTC
The knob on my keyboard increases the volume gradually as I turn it, but then MPV is focused, it shoots RIGHT up too 100 or back to 0 when only moving it once. This issue does not happen in stock MPV.

--input-test was blank to see what was causing it.

**Comment by stax76** [comment] 2020-04-12 19:47
Could you please rephrase and add details.

Is it button or a wheel or what is it?

It works in mpv and not in mpv.net?

If you run the command line `mpvnet --input-test` and press the knob it shows exactly what?

**Comment by AE720** [comment] 2020-04-18 20:12
It's a wheel. Here's a picture I found of it 
![image](https://user-images.githubusercontent.com/63013864/79670203-4a97f300-818f-11ea-8ae1-b4e8de21c63b.png)

It increases the volume gradually as I turn the knob. It does this in regular mpv as well. But anytime MPV.net is in focus one little turn will SHOOT it drastically to 100 and one turn down will decrease it to 12. --input test yielded no result when turning it but it did when I pressed other buttons

**Comment by stax76** [comment] 2020-04-19 17:10
Thanks for the info, what does mpv show with --input-test ?

**Comment by AE720** [comment] 2020-04-20 00:45
Literally nothing. Just like as if it was running without --input test but mouse movement, and other keys give a message in the top left. But not when I increase the volume.

**Comment by stax76** [comment] 2020-04-21 01:15
It's difficult to fix without hardware, this blue bar you see is not from mpv or mpv.net but from somewhere else. If mpv don't react with --input-test then it's somehow unlikely that mpv changes the volume.

**Comment by AE720** [comment] 2020-04-21 22:41
I understand the blue bar is the volume in Windows. I have demonstrated for you that this happens only when MPV.net is in focus. This doesn't occur anywhere else. Even in the original MPV so that is what is called a bug. It's one thing to say without anything from the --input-test you wouldn't know have the faintest idea how to fix it. But it's another to claim it's unlikely when I did my due process in proving that there is a bug in the software. If there is another method of obtaining information, I'll be happy to share. Otherwise it would help to figure out what changes under the hood you personally did to cause it.

**Comment by stax76** [comment] 2020-04-22 04:18
Technically it's very complicated. Maybe I can get such a keyboard.

**Comment by 44vince44** [comment] 2020-04-23 09:19
On an old win7 32b I had same issue with the volume knob. But I guessed it was either 32b issue or Win7 issue, or knob (old toshiba laptop model 2008), and old version of mpvnet. So It didn't matter...

**Comment by stax76** [comment] 2020-04-23 14:52
I've tried a virtual key software named Hot Virtual Keyboard, result was that mpv and mpv.net behave exactly the same, both had VOLUME_UP and VOLUME_DOWN in input.conf, both showed no reaction using  --input-test or volume change, both showed the blue bar of the system with normal gradual behavior. I've configured Spy++ to log which messages were sent, it was default virtual key codes VK_VOLUME_UP and VK_VOLUME_DOWN.

What I don't understand is why does mpv not react?

So far I can use Hot Virtual Keyboard for free but it constantly shows nag screens telling that the trial period is already over, I had used it before for debugging.

I know there is a crappy API called app commands that also have a volume command and I know some crappy drivers send both virtual key codes and app commands.

I'm going to do a code review for the input message code and check ebay if I can find such a keyboard.

**Comment by 44vince44** [comment] 2020-04-23 16:39
I would do tests on that old laptop, but i don't have it right now here. However in a few days, I can get it back for testing.

**Comment by stax76** [comment] 2020-04-23 21:04
OK, please try 5.4.4.5 Beta.

https://github.com/stax76/mpv.net#download

If that don't help then somebody has to send me the window messages recorded with Spy++ or I need to find and buy this hardware.

**Comment by 44vince44** [comment] 2020-04-24 06:48
@AE720  please test the latest beta, I can't do so right now because I won't have access to the laptop that has a volume knob before 5 days due to confinement restrictions.

**Comment by 44vince44** [comment] 2020-05-02 09:11
@stax76 I could work on that old laptop with the volume knob, and I downloaded and tested latest version 5.4.5.0 (x86 because that laptop's setup is x86).

The bad behaviour is still there BUT THERE IS A CHANGE, that the volume goes 0-x%-100%.
x is sometimes 42, sometimes 60.... So now there is ONE intermediate step between 0 and 100.

With older version of mpv.net, it only did 0-100%, no intermediate step. 

And of course, if mpv.net is NOT focused, then volume goes 0-v1-v2-...-v15-100,
(15 intermediate steps)

And I compared with mpv from mpv.io, there is no problem at all, volume works fine.

NOTE: in --input-test mode, there is no message, for both mpv.net and mpv.

**Comment by stax76** [comment] 2020-05-03 06:16
@44vince44

Thanks for testing. I did another small change in the next build. I can probably write a small tool to record the messages or upload spy++ and write a small tutorial how to record the messages or maybe I can buy the keyboard somewhere.

**Comment by 44vince44** [comment] 2020-05-03 15:10
Well, i'll test it, but i need the x32 version!

**Comment by stax76** [comment] 2020-05-04 02:01
Amazon don't seem to sell something similar.

**Comment by stax76** [comment] 2020-05-04 04:19
@44vince44 

New stable release is out. If it still doesn't work I can upload spy++ with description how to record window messages.

**Comment by 44vince44** [comment] 2020-05-04 04:43
I should be able to test in two days :-)) (my old laptop is not with me right now)

**Comment by stax76** [comment] 2020-05-04 05:00
OK, here is the spy++ download:

http://www.mediafire.com/file/50ejqag3arxcugh/Tools.7z/file

in the terminal start mpv:

`mpv --profile=pseudo-gui`

start spyxx_amd64.exe and in the main menu select:

Search > Find Window

drag & drop the cross on the mpv window and click OK in spy++

right click the mpv window tree view item and select Messages

activate the mpv window and turn the volume wheel

spy++ should list received messages

in the main menu select:

Messages > Save log file

that's it, post the content of the file

**Comment by 44vince44** [comment] 2020-05-04 07:16
Ok I got it, I guess i'll be using spyxx.exe and not spyxx_amd64 because the laptop with the knob is x32 not x64. I'll probably have this laptop again on wednesday, and try all of this then.

**Comment by stax76** [comment] 2020-05-04 13:35
Alright, thank you.

**Comment by 44vince44** [comment] 2020-05-05 17:24
@stax76 I'm on this old laptop and I did this:
1) because when i did "mpvnet --profile=pseudo-gui" i got an error saying that it's incompatible with my system x86 etc.., **so i put in mpv.conf the line "profile=pseudo-gui"**
(it's strange that the executable works, but not command line)
2) this version 5.4.6.0 still has the bug: when mpvnet is focused, then volume knob makes system audio volume jump from 0 to 100 and back to 0. But if mpvnet is not focused then system volume changes smoothly.
3) I did what you asked with spy++ and here is the message capture log: 
[log_vol_rotating_knob.zip](https://github.com/stax76/mpv.net/files/4582499/log_vol_rotating_knob.zip)

4) then i did the same, but only making the knob move ONE step up, and saved the log, cleared the log, then again with ONE step down, and saved the log. so this zip file has two logs
[log_vol_ONE_STEP_rotating_knob.zip](https://github.com/stax76/mpv.net/files/4582548/log_vol_ONE_STEP_rotating_knob.zip)


I hope this helps

**Comment by stax76** [comment] 2020-05-06 17:23
Please please be fixed now. New release is out.

https://github.com/stax76/mpv.net/releases

**Comment by 44vince44** [comment] 2020-05-06 18:30
@stax76 I tried the build 5.4.7.0, and thebehaviour has changed. now, when mpvnet is focused, moving the knob does nothing too the system audio volume ! the volume doesn't change at all!
Here is the message capture:
[one_step_up_v5.4.7.0.zip](https://github.com/stax76/mpv.net/files/4588737/one_step_up_v5.4.7.0.zip)

**Comment by stax76** [comment] 2020-05-07 02:52
@44vince44 

There are two types of keys:

regular virtual key code based keys and

app command based keys, mpv calls them media keys and has a property for them:

input-media-keys
Enable/disable media keys support. Enabled by default (except for libmpv).

For some keys like the volume there is both a virtual and a command key version and there might be differences in operating systems, GUI frameworks, in the hardware and drivers, so we have a really mad mess here! It's insane!

I did some research and have some ideas, it might take some time and be much work but I promise to work on this and take it more seriously. Unfortunately my health is not good and I might have to take a break.

**Comment by 44vince44** [comment] 2020-05-07 03:22
@stax76 yes you've been working too much lately! get some rest !!! all this stuff can wait.
Catch you later when you'll feel good. Take care!!

**Comment by stax76** [comment] 2020-05-08 07:39
I try to relax today. There is a new beta trying a new approach to fix this. I hope it's working this time. 🤞 🙂

5.4.7.2 Beta

Changelog:

https://github.com/stax76/mpv.net/blob/master/Changelog.md

Download:

https://github.com/stax76/mpv.net/blob/master/Manual.md#beta

**Comment by 44vince44** [comment] 2020-05-08 08:32
downloading and trying (BTW, this issue is not important for me because the laptop with the volume knob is old, i don't use it anymore: outdated hardware with outdated unsupported os: win7... so I was only trying to help user AE720 who has the same issue, and maybe other users that will get this kind of keyboard). testing in a few minutes

**Comment by 44vince44** [comment] 2020-05-08 08:53
Couldn't test v5.4.7.2 because the x86 version in the v5.4.7.2 is actually v5.4.7.0.
It seems that the x86 archive has not been updated (executable says 5.4.7.0 and is dated 2 days ago)

**Comment by stax76** [comment] 2020-05-08 12:31
Sorry was a bug in my release script. I do first research a bit further and after that probably add a setting with 3 modes. I greatly appreciate your help.

**Comment by 44vince44** [comment] 2020-05-08 13:05
OK I'm waiting, when the x86 version is available, just drop me a line!

**Comment by stax76** [comment] 2020-05-08 13:51
There is now a setting `media-keys` with 4 different options, can be found in the config editor in the input tab.

Download:

https://github.com/stax76/mpv.net/blob/master/Manual.md#beta

If it's still not working then we are either close or it's too difficult to solve and I can probably explain why it's too difficult.

**Comment by 44vince44** [comment] 2020-05-08 14:53
Ok thanks @stax76  for this beta which shows good progress ! Actually 50% good.

- turn the knob "UP": WORKS PERFECTLY, **system audio volume increased step by step, gradually and smoothly**, mpvnet audio don't change. **This is the expected behaviour !!!**
- turn the knob "DOWN": system audio doesn't change, but mpv audio volume decreases smoothly. This is not the expected behaviour, but it is not wrong!

So what's next Stax?

**Comment by 44vince44** [comment] 2020-05-08 15:28
But it seems the behaviour of all multimedia keys of the keyboard change.
I must do a few more tests

**Comment by 44vince44** [comment] 2020-05-08 15:48
@ stax, Ok I did many tests, involving 2 laptops, the result is simple:
 -> media-keys = mpvnet should be the only option possible, but it needs ONLY one change:
  the VK_VOLUME_DOWN must be changed to act like the VK_VOLUME_UP, and VK_volume_UP must not be changed.

**Comment by 44vince44** [comment] 2020-05-08 16:00
@stax76  I confirm**, please read this,** (the previous posts are almost useless):

Modes "discard", "mpv", " pass" are working as expected -> GOOD (but they are not useful)
Mode "mpvnet" IS USEFUL, and is working as expected for ALL MULTIMEDIA KEYS except for VK_VOLUME_DOWN. VK_VOLUME_DOWN must be treated as currently is VK_MUTE and VK_VOLUME_UP.

**Comment by stax76** [comment] 2020-05-08 16:19
Thanks for the thorough tests and information. 👍

I keep working and researching on it.

**Comment by 44vince44** [comment] 2020-05-08 16:24
@stax76 I noticed in the commits, that currently, the cases are assigned like this:
                case 1:  return "VOLUME_UP";    // VOLUME_UP
                case 9:  return "VOLUME_DOWN";  // VOLUME_DOWN
                case 8:  return "MUTE";         // VOLUME_MUTE

But in the previous numbers assigned, VOLUME_UP WAS 10, not 1.
And volume up is working correctly!!

**Comment by stax76** [comment] 2020-05-08 16:31
Oh sorry, I lost a zero (will check the full list now).

**Comment by 44vince44** [comment] 2020-05-08 16:42
Well maybe that's why this one is working correctly, because it is excluded from processing in mode "mpvnet" due to the error (the lost zero).
So this is what we have to do : in mode "mpvnet", process all keys except volume_up and volume_down, which makes sense, because you need all commands to act on mpvnet, except commands volume_up and volume_down, because they have to act on the system.
So I suggest you keep this mistake, and you create a mistake on volume_down.

**Comment by stax76** [comment] 2020-05-10 05:06
Thanks for the great help Vince, it's much likely fixed now!

5.4.7.4 Beta

Changelog:

https://github.com/stax76/mpv.net/blob/master/Changelog.md

Download:

https://github.com/stax76/mpv.net/blob/master/Manual.md#beta

**Closed by stax76** 2020-05-10 05:06 UTC
Labels: enhancement

**Comment by 44vince44** [comment] 2020-05-10 09:45
@stax76 Thanks to you !! I tested it and it's fully working as expected !!! Thanks again !
