### ISSUE TITLE
Autofit and remember-height interaction bug and incorrect behavior

### ISSUE THREAD

**Issue by derude50** [stax76/mpv.net#42] opened 2019-07-11 14:02 UTC
Current behavior: If Remember-height: No is selected, the window will first size the window to the Autofit: N% value, then it will again resize to the native video resolution. This causes the video to load slower, and causes the window to quickly resize twice before the video begins to play, leading to a jarring visual effect I've seen many complain about when discussing the mpv.net video player. 

Expected behavior: If Remember-height: No is selected, the native video resolution should be the first and only size of the window, unless the window size is greater than the monitor resolution. If the window size is greater than the monitor resolution, it should size the window to the maximum resolution of the monitor. You can look to MPC-HC for an example of how this is implemented.

Additional suggestion: Remember-height and autofit settings should probably be renamed and reorganized to a toggle between these two options: "Always use video resolution as window size" and "Always set the window size to: N%." I've seen many people not understanding what Remember-height does and not understanding what it's supposed to do, given its interaction with Autofit. It doesn't make much sense for both of them to activate at the same time.

**Comment by ScottRFrost** [comment] 2019-07-11 15:13
This is not a new issue / regression with the current version.  As long as I've been using MPV.net this has never actually worked.  Not only does it not save height but it doesn't save position / whether it was maximized / etc.

I'd love an option for "Always start maximized on monitor 2"

**Comment by stax76** [comment] 2019-07-11 16:59
@derude50 

I can try to implement that it starts with the video size, thanks for pointing it out. I don't understand though how you would organize it better.

@ScottRFrost 

For this you can use 'fullscreen' yes and 'screen' as zero based index.

**Comment by ScottRFrost** [comment] 2019-07-11 19:10
Hi @stax76 !

Is it possible to save window position (top left corner X,Y last time mpv.net was open, next time it opens it goes back to X,Y)?  Mine starts arbitrarily in the middle of my 2nd screen and I can't change it no matter what I do.  Also if it's possible to start as a maximized window instead of fullscreen, that would be awesome!

**Comment by stax76** [comment] 2019-07-11 19:46
Hi Scott, I try to implement starting directly with the native video size first, I think I almost got it now, after 3 hours debugging, it's not as easy as it seems, quite a bit threading involved and that's always a bit difficult.

I might not be able to implement all requests due to health problems, we'll see.

**Comment by derude50** [comment] 2019-07-11 20:15
@stax76 Thanks for the reply and your hard work. The reason I suggest re-organizing the settings is because it does not make sense to have both Remember-Size and Autofit enabled at the same time. It's not logical to want the window size at 80% of the monitor and also want native video resolution size at the same time. This is why there is the unwanted behavior of two different window resizes occurring. It's not meant for both to be used at the same time. The reason these options exist is because they are merely configuration options / command line arguments. It does not make much sense in a GUI settings menu to enable both. The GUI should restrict to only choosing one or the other. I hope I explained it better, I can elaborate further if needed.

(And it is also very important that if the native video resolution is larger than the monitor resolution, the window should not extend past the monitor size and cut off the video.)

**Comment by ScottRFrost** [comment] 2019-07-11 20:16
I don't know if it's helpful or not, but SMplayer also implements mpv under the hood and it remembers window top,left,width,height.  If you close it then double click a movie file to re-open it, it opens in the same position and size that it was at when you closed it.

**Comment by stax76** [comment] 2019-07-11 22:08
@ScottRFrost 

Remembering the position and size is very simple so looking at the source of another players is not needed. Implementing something simple can sometimes still cause much work though.

@derude50 

I've renamed it a little and hope its clearer now.

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

- remember-height was replaced with start-size, when start-size is set
  to video the main video starts directly with the native video size,
  before it was starting with the autofit size first and was only
  afterwards resized to the native video size

It took me a few hours, I hope it's stable.

**Comment by derude50** [comment] 2019-07-12 00:15
@stax76 That's working a lot better and is more clear. Nicely done. Worked fine with the different videos I tested too.

**Comment by stax76** [comment] 2019-07-12 04:17
@derude50 

My tests are good so far too.

@ScottRFrost 

Remembering the size and maximized state on exit is not yet supported, please create new issues if you think it's important. Next build supports:

remember-position: mpv.net specific setting to save the window position on exit.

**Comment by stax76** [comment] 2019-07-12 04:19
I'll close the issue after a new release is out.

**Comment by 44vince44** [comment] 2019-07-12 18:06
I hope the health problems are not serious health problems Stax !!

**Comment by stax76** [comment] 2019-07-13 02:59
> I hope the health problems are not serious health problems Stax !!

Thanks, Vince. It could be worse, the condition is called CFS/FMS, it makes coding anything complex very difficult because I get much pain and bad sleep afterwards.

The new release is out, it has some optimization regarding features discussed in this thread/issue.

https://github.com/stax76/mpv.net/releases

**Closed by stax76** 2019-07-13 02:59 UTC

**Comment by ScottRFrost** [comment] 2019-08-14 17:19
Hi @stax76 !  

Just tried on 5.3.0.0, but it's not clear on what to do to get this to work

> Next build supports:
> 
> remember-position: mpv.net specific setting to save the window position on exit.

**Comment by stax76** [comment] 2019-08-14 17:56
Hi Scott,

remember-position is a config setting you can find in the config dialog at the end of the screen section, alternatively you can find it using the search feature. It saves the window position on exit and restores it on start.

**Comment by mchubby** [comment] 2021-01-10 13:32
Hello @stax76,

I'm trying to get mpv.net to always open at the same position (top-left corner of first monitor).
Currently using an early 2021 build (from the onedrive link in Manual.md).

The configuration is set using the editor
```
start-size = video
remember-position = yes
```

Scenario is :

1. open a 720p file (1280x720), drag window to desired position
2. Close => registry `PosX=640, PosY=360`
3. open a 1080p file (1920x1080) => top position is good, left position is too far left.
4. Close `PosX=640, PosY=540`
5. open a 720p file => position is no longer okay.
6. Close `PosX=640, PosY=540`

As I understand it, the position is set relative to the video center point or something, and we only remember the height.

Maybe also related to #140 which was marked as super low priority, sadly.

**Comment by stax76** [comment] 2021-01-11 00:42
It just saves the center position. There are currently no plans for a more advanced method.

If you like you can try if there are other players using a better method to save and restore the position. That would be interesting to know.

**Comment by mchubby** [comment] 2021-03-04 21:09
I have worked around the issue by using the powertoys' Fancy Zones feature.

**Comment by ScottRFrost** [comment] 2021-03-05 16:10
> If you like you can try if there are other players using a better method to save and restore the position. That would be interesting to know.

SMPlayer (which also uses MPV under the hood) and VLC both save entire window position on close, as long as you disable resizing the interface to the video size.  Disabling resizing is the default option for both, if I recall correctly.

![image](https://user-images.githubusercontent.com/3866418/110141490-322ec800-7da3-11eb-914f-1b2c54bdd6b3.png)

![image](https://user-images.githubusercontent.com/3866418/110141609-58546800-7da3-11eb-9979-fb95f3aa6dcf.png)
